TCP通信用の機能の追加
tmcit-2024-adv-prog/quantum-gomoku pull request #26
Opened 2024-11-19 05:12 UTC by 5hrz

本PRでは以下の機能を追加します。

- TCPを用いた通信機能

なお、本PRでは他クラスとの連携を行なっていないため、TODOが残っています。

本機能を追加する際には以下のように記載します。

```java

public void someSenderSideMethod() {
    // 接続を最初に受け待つ側の処理
    TCPSocket tcpSocket = new TCPSocket(new TCPSocketProps(null, 5050));
    // ソケットの初期化
    tcpSocket.initSender();
    // 接続相手からの通信を待ち受ける
    tcpSocket.startReceive();
}

public void someReceiverSideMethod() {
    // 接続を最初に受け待つ側の処理
    TCPSocket tcpSocket = new TCPSocket(new TCPSocketProps("192.168.100.1", 5050));
    // ソケットの初期化
    tcpSocket.initReceiver();
    // 接続相手からの通信を待ち受ける
    tcpSocket.startReceive();
}
```

2024-11-30 16:34 UTC, cffnpwr requested changes
- rebaseしてほしい
- Receiver Senderのインターフェイスはinterfacesディレクトリに移動してほしい
- GameStatusはGameStateに改名されました
  - GameStateは試合の状態（盤上の石の配置とかプレイヤーの情報とか手番の情報とか）を持つオブジェクトにしてほしい（具体的なクラスの実装は試合担当の実装を待つ）

2024-12-01 11:26 UTC, 5hrz commented
> - rebaseしてほしい
>
> - Receiver Senderのインターフェイスはinterfacesディレクトリに移動してほしい

後ほど対応します

> - GameStatusはGameStateに改名されました
> 
>   - GameStateは試合の状態（盤上の石の配置とかプレイヤーの情報とか手番の情報とか）を持つオブジェクトにしてほしい（具体的なクラスの実装は試合担当の実装を待つ）

Serializableを保ってもらえればどのような構造であっても送受信できるようにしてあるので一旦TODO統合時に調整したいです

2024-12-01 12:54 UTC, cffnpwr commented
> > * rebaseしてほしい
> > * Receiver Senderのインターフェイスはinterfacesディレクトリに移動してほしい
> 
> 後ほど対応します
> 
> > * GameStatusはGameStateに改名されました
> >   
> >   * GameStateは試合の状態（盤上の石の配置とかプレイヤーの情報とか手番の情報とか）を持つオブジェクトにしてほしい（具体的なクラスの実装は試合担当の実装を待つ）
> 
> Serializableを保ってもらえればどのような構造であっても送受信できるようにしてあるので一旦TODO統合時に調整したいです

把握しました
対応後にapproveしてマージします

あと、完全に忘れてましたが、GameState（GameStatusだったもの）はmodelsディレクトリに移動してほしいです

2024-12-02 11:27 UTC, 5hrz commented
ごめんなさいめちゃくちゃコミットログ荒らしました

2024-12-02 12:05 UTC, cffnpwr approved these changes
LGTM

2024-12-02 12:05 UTC, cffnpwr commented
> Overall Project	10.64% **`-6.38%`**	❌
> Files changed	0%	❌
> 
> File	Coverage	
> [GameState.java](https://github.com/tmcit-2024-adv-prog/quantum-gomoku/blob/af6b5fffb6d741a2a3668699756d22a5ffb3848a/app%2Fsrc%2Fmain%2Fjava%2Fjp%2Fac%2Fmetro_cit%2Fadv_prog_2024%2Fgomoku%2Fmodels%2FGameState.java)	0%	❌

カバレッジちゃんと出てないな

2024-12-02 12:05 UTC, merged