feat: 石及び石の色における機能の追加
tmcit-2024-adv-prog/quantum-gomoku pull request #38
Opened 2024-11-29 06:02 UTC by RyuseiHoshi

石及び石の色における機能の追加。
石クラスを担当しているので、石クラス及び石の色クラスを作成しました。
石クラスでは、色、Xポジション、Yポジションのreturnが可。
石の色クラスでは、石の色をenumで設ける。
って感じになってます。

2024-11-29 06:13 UTC, sMontake369 commented
石の色には黒、白、未定の3つが存在する。また、色を途中で変更する可能性がある場合、色を変更する関数を作成する必要がある。

![image](https://github.com/user-attachments/assets/6f4c86f8-075c-4c35-88e4-309d88e42fc4)

2024-11-29 06:33 UTC, MisoHaUmi requested changes

2024-11-29 06:33 UTC, MisoHaUmi commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/StoneColor.java
石の色にEMPTY（未設置）を追加してほしいです。

2024-11-29 06:43 UTC, RyuseiHoshi commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/StoneColor.java
石の色にEMPTY（未登録）を追加しました。ご確認願います。

2024-11-29 06:49 UTC, MisoHaUmi commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/StoneColor.java
確認しました。

2024-11-29 06:49 UTC, MisoHaUmi submitted a review, later dismissed

2024-11-29 06:54 UTC, cffnpwr commented
> 石の色には黒、白、未定の3つが存在する。また、色を途中で変更する可能性がある場合、色を変更する関数を作成する必要がある。
> 
> ![image](https://private-user-images.githubusercontent.com/167681634/390982387-6f4c86f8-075c-4c35-88e4-309d88e42fc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NjMxNTYsIm5iZiI6MTczMjg2Mjg1NiwicGF0aCI6Ii8xNjc2ODE2MzQvMzkwOTgyMzg3LTZmNGM4NmY4LTA3NWMtNGMzNS04OGU0LTMwOWQ4OGU0MmZjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOVQwNjQ3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTk3OWM4MWRjMGRmZWU3NTBlOTQ0MjhlYzE2M2EyNjZlNDBmYmI3Yjc2MDFhZmM1YTE0OTUyODAwOTA4MTQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cY0a0FnIVzjoAaoNr6CcJwF9lXIG6IszbA8T98eXM0s)

色って途中で変更されるんですか？

2024-11-29 07:20 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/StoneColor.java
> +  EMPTY;
EMPTYは不要になったので消してください

2024-11-29 08:00 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/StoneColor.java
> +  EMPTY;
ドキュメントの方のクラス図も書き換えて

2024-11-29 09:15 UTC, RyuseiHoshi commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/StoneColor.java
> +  EMPTY;
未定消しました。確認を願います。

2024-11-29 09:24 UTC, RyuseiHoshi commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/StoneColor.java
> +  EMPTY;
ドキュメントのクラス図も書き換えました。

2024-12-27 11:46 UTC, sMontake369 requested changes
コメントしました。修正お願いします。

2024-12-27 11:46 UTC, sMontake369 commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Stone.java
> +  @Nullable
Stoneの色が未定な状態は存在しないと思います。万が一、ある場合、setColor等の関数を作成する必要があると思います。

2024-12-27 11:46 UTC, sMontake369 commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Stone.java
> +   * 医師の座標を返す。
誤字

2024-12-27 11:46 UTC, sMontake369 commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Vector2D.java
> + * @author 6306 hoshi
このクラスは既に私が作成しています。まるであなたが作成したように書かれるのは、少し悲しいです。すでにmainブランチにあるので、このファイルはマージしないでほしいです。

2024-12-30 10:51 UTC, sMontake369 submitted a review, later dismissed
spotbugsとconflictを修正すれば問題ないと思います

2024-12-31 15:29 UTC, cffnpwr requested changes
テストを実装してください

2024-12-31 15:29 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Stone.java
>    }
これ消さないでほしい

2025-01-06 11:57 UTC, cffnpwr requested changes

2025-01-06 11:57 UTC, cffnpwr commented on app/src/test/java/jp/ac/metro_cit/adv_prog_2024/gomoku/StoneTest.java
> +    Vector2D testposition = new Vector2D(3, 4);
lowerCamelCaseで変数を宣言してください

2025-01-06 11:57 UTC, cffnpwr commented on app/src/test/java/jp/ac/metro_cit/adv_prog_2024/gomoku/StoneTest.java
> +    Stone teststone2 = new Stone(testcolor, testposition);
lowerCamelCaseで変数を宣言してください

2025-01-06 11:57 UTC, cffnpwr commented on app/src/test/java/jp/ac/metro_cit/adv_prog_2024/gomoku/StoneTest.java
> +    Stone teststone2 = new Stone(testcolor2, testposition);
lowerCamelCaseで変数を宣言してください

2025-01-06 11:57 UTC, cffnpwr commented on app/src/test/java/jp/ac/metro_cit/adv_prog_2024/gomoku/StoneTest.java
> +    Stone teststone2 = new Stone(testcolor, testposition2);
lowerCamelCaseで変数を宣言してください

2025-01-06 11:57 UTC, cffnpwr commented on app/src/test/java/jp/ac/metro_cit/adv_prog_2024/gomoku/StoneTest.java
> +    Stone teststone = new Stone(testcolor, testposition);
lowerCamelCaseで変数を宣言してください

2025-01-06 11:57 UTC, cffnpwr commented on app/src/test/java/jp/ac/metro_cit/adv_prog_2024/gomoku/StoneTest.java
> +    Stone teststone2 = new Stone(testcolor, testposition);
lowerCamelCaseで変数を宣言してください

2025-01-06 11:57 UTC, cffnpwr commented on app/src/test/java/jp/ac/metro_cit/adv_prog_2024/gomoku/StoneTest.java
> +    Stone teststone2 = new Stone(testcolor2, testposition);
lowerCamelCaseで変数を宣言してください

2025-01-06 11:58 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Stone.java
> +    return position;
このメソッド名の変更はStoneクラスに依存しているクラスの実装担当者と合意が取れていますか？

2025-01-08 15:43 UTC, cffnpwr requested changes

2025-01-08 15:43 UTC, cffnpwr commented on .github/workflows/ci.yaml
> +    runs-on: ubuntu-latest
勝手に変えないで

2025-01-08 15:43 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Player.java
>    }
勝手に消さないで

2025-01-08 15:43 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Stone.java
> +   */
勝手な解釈で自分が実装してない部分のJavadocを書かないでください

2025-01-08 15:43 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Stone.java
> +   */
上と同じです

2025-01-08 15:43 UTC, cffnpwr commented on app/src/test/java/jp/ac/metro_cit/adv_prog_2024/gomoku/StoneTest.java
> +  @DisplayName("[正常系] stoneオブジェクトの初期状態が正しく設定される")
正しいとはどういう状態ですか？

2025-01-08 15:43 UTC, cffnpwr commented on app/src/test/java/jp/ac/metro_cit/adv_prog_2024/gomoku/StoneTest.java
> +  @DisplayName("[正常系] stoneオブジェクトがhashCodeで正しくハッシュを計算する")
正しいとはどういう状態ですか？

2025-01-21 04:56 UTC, MisoHaUmi reviewed
Stoneクラスは問題ないと思います。

2025-02-03 07:24 UTC, cffnpwr approved these changes

2025-02-03 07:28 UTC, closed without merging