feat: プレイヤークラスの機能の追加
tmcit-2024-adv-prog/quantum-gomoku pull request #39
Opened 2024-11-29 09:49 UTC by RyuseiHoshi

プレイヤークラスにおける機能の追加。
石の色、プレイヤーネームのreturnが可。
って感じになってます。

2024-11-29 14:30 UTC, cffnpwr approved these changes
LGTM

2024-12-01 15:30 UTC, cffnpwr requested changes

2024-12-01 15:30 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Player.java
javadocで各メソッドの説明を書いてほしい

2024-12-01 15:30 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Stone.java
javadoc書いて

2024-12-03 04:58 UTC, RyuseiHoshi commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Player.java
javadocの追記をしたので、ご確認願います。

2024-12-03 04:58 UTC, RyuseiHoshi commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Stone.java
Player.java同様、javadocのご確認願います。

2024-12-03 04:59 UTC, cffnpwr approved these changes

2024-12-03 05:00 UTC, cffnpwr commented
rebaseだけお願いします

2024-12-03 05:02 UTC, cffnpwr requested changes
プレイヤーの色を設定するメソッドを実装してください

2024-12-06 03:37 UTC, cffnpwr requested changes

2024-12-06 03:37 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Player.java
> +  private StoneColor color;
プレイヤーの色は未定状態として`null`を取るようにしてください

2024-12-06 03:37 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Player.java
> +  }
色は初期で`null`を取るようにしてください

2024-12-06 03:37 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Player.java
> +  }
あとから色を上書きできないようにしてください

2024-12-17 11:38 UTC, cffnpwr requested changes
コミット add252487bce50554dc0ef5338e113ad18407a9f のコミットメッセージが長すぎます

2024-12-17 11:38 UTC, cffnpwr commented on app/src/test/java/jp/ac/metro_cit/adv_prog_2024/gomoku/PlayerTest.java
> +    assertEquals(StoneColor.WHITE, testplayer2.getColor(), "setColorで設定したWHITEが正しく取得されません");
2つのテストは同じテストメソッドで行わないで、メソッドを分けてください

2024-12-17 11:38 UTC, cffnpwr commented on app/src/test/java/jp/ac/metro_cit/adv_prog_2024/gomoku/PlayerTest.java
> +  @DisplayName("[正常系]")
このテストの名称として`[正常系]`は不適切です
適切にテストの内容を名称に設定してください

2024-12-17 11:38 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Player.java
> +  }
Nullを返しうるメソッドには`@Nullable`アノテーションをつけてください
javadocにもnullを返しうること、その条件を書いてください

2024-12-17 13:33 UTC, sMontake369 requested changes
全体的に、Vector2Dクラスを使用した実装に変更してください

2024-12-17 13:33 UTC, sMontake369 commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Stone.java
> +  }
Vector2Dクラスを使用してください

2024-12-17 13:33 UTC, sMontake369 commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Stone.java
> +  }
同じく

2024-12-17 13:33 UTC, sMontake369 commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Stone.java
> +  private int posY;
Vector2Dクラスを使用してください

2024-12-27 11:48 UTC, sMontake369 reviewed
Vector2Dが使われていませんが[石のプルリクエスト](https://github.com/tmcit-2024-adv-prog/quantum-gomoku/pull/38)で正しく使用されていれば、問題ないと思います。

2024-12-27 11:49 UTC, sMontake369 submitted a review, later dismissed

2025-01-08 15:48 UTC, cffnpwr requested changes

2025-01-08 15:48 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Player.java
>    public void setColor(StoneColor color) {
発生しうる例外をthrowsで定義してください

2025-01-08 15:48 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Player.java
>    }
勝手に消さないで

2025-02-03 07:22 UTC, cffnpwr approved these changes

2025-02-03 07:23 UTC, merged