再:試合クラスの追加
tmcit-2024-adv-prog/quantum-gomoku pull request #47
Opened 2024-12-03 13:45 UTC by sMontake369

ブランチを変えて再度pull requesutします
本PRでは以下のクラスを実装

## Vector2Dクラス
### 概要
2次元座標を扱うクラス

## Gameクラス
### 概要
ゲーム全体を管理し、五目並べのシステムを統括するクラス
### 機能
・試合の開始
・盤に石を設置
・勝利判定

2024-12-03 15:02 UTC, cffnpwr requested changes
テストに関しては私がドキュメントを書けていないのでドキュメントが書けてから再度レビューします

2024-12-03 15:02 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/exceptions/PutStoneException.java
> +  public PutStoneException(String message) {
ここのメッセージはどのような値が入りますか？
javadocを書いてください

2024-12-03 15:02 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/GamePhase.java
> +  END,
開始前の訳がsetup、終了済みの訳がendで妥当である根拠はありますか？
開始前はbrefore_start、終了済みはendedやfinishedの方が妥当であるように思えます。

2024-12-03 15:02 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Vector2D.java
> +  public int y;
この変数はpublicで宣言されていますが、外部から変更可能な理由はありますか？
外部から編集可能である必要がないのであれば、privateにしてgetterを実装するべきです。

2024-12-03 15:02 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Vector2D.java
javadoc書いて

2024-12-03 15:02 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/services/Game.java
> +  private Player player2;
player1、player2という命名はなにか意図があって1、2にしていますか？
意図がないのであれば実装を鑑みるにblackPlayer、whitePlayerのように変数名からデータの中身を推測可能な名前にするのが良いと思います

2024-12-03 15:02 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/services/Game.java
> +      return;
この場合は`PutStoneException`をthrowするべきではないですか？
正常系で終了している理由があれば説明がほしいです。

2024-12-03 15:02 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/services/Game.java
> +  public void setGameState(GameState state) {}
実装忘れ？

2024-12-03 15:02 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/services/Game.java
> +    board.show();
`board.show()`をここで実行する意図はなんですか？

2024-12-03 15:02 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/services/Game.java
> +    gameState = new GameState("Game is not started yet");
メンバ変数は`this.hoge`のように記述してください。
メンバ変数なのか、ローカル変数なのかわからなくなります。

2024-12-03 15:19 UTC, mntk369 commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Vector2D.java
> +  public int y;
全てのメンバはprivateでなければならないのですか。
x,yについてもgetterを設定すると、全てのVector2Dが
```java
Vector2D pos = new Vecto2D(stone.pos.getPosX(), stone.pos.getPosY());
```
のように冗長で可読性が低くなると思います。

```java
Vector2D pos = new Vecto2D(stone.pos.x, stone.pos.y);
```
それでもなお、privateにするべきというのなら修正します。
僕は反対です。

2024-12-03 15:27 UTC, sMontake369 commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/services/Game.java
> +  public void setGameState(GameState state) {}
gameStateとは何ですか。
class-diagram.mdにはStateを表すメソッドやデータは見当たりません。

2024-12-03 15:36 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Vector2D.java
> +  public int y;
Stoneクラスの方に下のようなメソッドを実装してもらうのはどうでしょうか？

```java
Vector2D pos = stone.getPosVec()
```

2024-12-03 15:52 UTC, sMontake369 commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/exceptions/PutStoneException.java
> +  public PutStoneException(String message) {
自分が作成したものではないので削除

2024-12-03 15:52 UTC, sMontake369 commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/services/Game.java
> +  public void setGameState(GameState state) {}
自分が作成したものではないので削除

2024-12-03 16:02 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Vector2D.java
> +  public int y;
Recordを使うと良さそう？
https://dev.java/learn/records/

2024-12-03 16:10 UTC, mntk369 commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Vector2D.java
> +  public int y;
finalで解決します
```java
public class Vector2D {
  public final int x;
  public final int y;

  public Vector2D(int x, int y) {
    this.x = x;
    this.y = y;
  }
}
```

2024-12-03 16:54 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/services/Game.java
> +}
盤の方で実装されるべきかも？

2024-12-04 01:34 UTC, MisoHaUmi requested changes
ファイル内容が他の担当と被ってる気がします。（既に結合してたらスマン）それぞれ担当と確認して欲しいです。

2024-12-04 01:34 UTC, MisoHaUmi commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Board.java
これ俺が作るところじゃね
俺盤クラス担当なんだが

2024-12-04 01:34 UTC, MisoHaUmi commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Color.java
ここも星が石の色担当してるはず

2024-12-04 04:05 UTC, sMontake369 commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Board.java
試合クラスを作るのに必要なので簡単に作成しました。まだ、Boradがマージされていないので、正しい引数がわかりません。GameクラスがそちらのBoardクラスに正しくアクセスできるか確認してください。

2024-12-04 04:06 UTC, sMontake369 commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Color.java
同様の理由

2024-12-04 07:13 UTC, MisoHaUmi commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/services/Game.java
> +}
こちらで一応考えてるものはあるので、盤の方で実装します

2024-12-04 07:15 UTC, MisoHaUmi commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Board.java
分かりました。

2024-12-06 02:25 UTC, RyuseiHoshi commented
大した違いはないんだけど、ColorクラスをStoneColorにして欲しい。
Colorってのと、colorってのが混在しているから異なることを見て分かるようにって個人的に感じました。

2024-12-06 02:26 UTC, RyuseiHoshi commented
> 大した違いはないんだけど、ColorクラスをStoneColorにして欲しい。 Colorってのと、colorってのが混在しているから異なることを見て分かるようにって個人的に感じました。

2024-12-06 02:36 UTC, RyuseiHoshi submitted a review, later dismissed
大竹の担当の試合に関しては問題ないかと思う。

2024-12-06 02:52 UTC, yanbaru1331 commented
横槍ですが、クラス等影響が全体に広がる議論はここでしないで下さい

2024-12-14 15:04 UTC, cffnpwr requested changes

2024-12-14 15:04 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/GamePhase.java
javadoc日本語になってませんよ

2024-12-14 15:04 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/models/Vector2D.java
javadoc日本語になってませんよ

2024-12-14 15:04 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/services/Game.java
> +    this.whitePlayer = new Player(null, whitePlayer.getName());
SuppressWarningしているならここは引数のplayerを直接代入して良いと思います

2024-12-14 15:04 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/services/Game.java
> +    this.board = new Board(board.getSize());
ここも同様に引数のboardを直接代入していいと思います

2024-12-14 15:04 UTC, cffnpwr commented on app/src/test/java/jp/ac/metro_cit/adv_prog_2024/gomoku/services/GameTest.java
これは私がドキュメントに書いてないのが悪いですが、テスト対象に依存クラスが存在する場合は依存クラス（このテストの場合は`Player`、`Board`）をmockito等のモックライブラリでモックしてテストを書いてほしいです。
参考: https://qiita.com/opengl-8080/items/dcdf2cb14f2642240a5b

2024-12-14 15:04 UTC, cffnpwr commented on app/src/test/java/jp/ac/metro_cit/adv_prog_2024/gomoku/services/GameTest.java
> +    }
この書き方だと、実装変更などで再度`startGame()`を呼び出したときに例外が投げられない状態になったときに、`catch`の中の`assertTrue`が評価されずにテストが通ってしまうので以下の2例のいずれかの形式で書くと良いと思います。

## try-catchで書く場合

```java
try {
  // ここで例外が発生することをテストしたい
  throwExceptionMethod();
  // 例外が発生しなかった場合はorg.junit.Assert.failで失敗させる
  fail();
} catch (Exception e) {
  assertTrue(e instanceof HogeException);
}
```

## assertThrowを使う場合

```java
// HogeExceptionが投げられることをテストする
assertThrow(HogeException.class, () -> throwExceptionMethod());
// assertThrowは投げられた例外を返す
HogeException expected = assertThrow(HogeException.class, () -> throwExceptionMethod());
// 投げられた例外の詳細（メッセージなど）もテスト可能
assertThat(expected.getMessage(), is("hogehoge"));
```

2024-12-14 15:04 UTC, cffnpwr commented on app/src/test/java/jp/ac/metro_cit/adv_prog_2024/gomoku/services/GameTest.java
> +    }
これ上と同様

2024-12-14 15:04 UTC, cffnpwr commented on app/src/test/java/jp/ac/metro_cit/adv_prog_2024/gomoku/services/GameTest.java
> +    }
これも上と同様

2024-12-14 15:04 UTC, cffnpwr commented on app/src/test/java/jp/ac/metro_cit/adv_prog_2024/gomoku/services/GameTest.java
> +    }
これも上と同様

2024-12-14 15:04 UTC, cffnpwr commented on app/src/test/java/jp/ac/metro_cit/adv_prog_2024/gomoku/services/GameTest.java
> +  }
このテストは開始前のテストが通らないと終了後のテストがそもそも走らないので、開始前と終了後2つに分けたほうが良いと思います。

2024-12-14 15:04 UTC, cffnpwr commented on app/src/test/java/jp/ac/metro_cit/adv_prog_2024/gomoku/services/GameTest.java
> +    }
これも上と同様

2024-12-14 15:04 UTC, cffnpwr commented on app/src/test/java/jp/ac/metro_cit/adv_prog_2024/gomoku/services/GameTest.java
> +    }
これも上と同様

2024-12-15 08:13 UTC, cffnpwr commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/services/Game.java
> +      throw new GamePlayerException("It is not your turn.");
ここの例外処理のテストがないのは意図的なものですか？

2024-12-17 05:21 UTC, cffnpwr approved these changes

2024-12-17 05:38 UTC, MisoHaUmi approved these changes

2024-12-17 05:42 UTC, merged