feat: マッチング処理の実装
tmcit-2024-adv-prog/quantum-gomoku pull request #53
Opened 2024-12-04 16:55 UTC by cffnpwr

## 概要

マッチング処理を実装しました
resolve: #43

2024-12-15 12:28 UTC, cffnpwr commented
メモリ不足でCIが通らん

2024-12-17 04:24 UTC, 5hrz requested changes

2024-12-17 04:24 UTC, 5hrz commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/controllers/MatchingControllerBuilder.java
> +public class MatchingControllerBuilder {
publicなメンバにjavadocを記載してください

2024-12-17 04:24 UTC, 5hrz commented on app/src/main/java/jp/ac/metro_cit/adv_prog_2024/gomoku/controllers/MatchingController.java
> +  public Player match() throws MatchingTimeoutException, MatchingFailedException {
全体的に(できればブロックごとに)処理の概要をコメントして欲しいです

2024-12-17 04:42 UTC, 5hrz submitted a review, later dismissed

2024-12-17 04:56 UTC, yanbaru1331 reviewed
実装はmd形式でできていることが実装できていると思うので特にチェックはしてないです
コメントでだいたい何をするのかわかったので

フェーズだけ修正しておいてください

2024-12-17 04:56 UTC, yanbaru1331 commented on docs/details-design/matching-ctrl.md
> +
これだと実際に試合が開始できないので、
上位/同列に実際に試合の実態を生成させるまでの処理を書いたほうがいいと思う
5. hogehogeにgameを生成させるみたいな

2025-01-06 14:16 UTC, yanbaru1331 approved these changes
動いてるからヨシ

2025-01-06 14:21 UTC, merged